name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild FuckDefender.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: FuckDefender
        path: |
          FuckDefender/bin/Release/FuckDefender.exe
